spring:
    application:
        name: spring-boot-react
#    datasource:
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://localhost:5432/match_engine
#        username: postgres
#        password: postgres
    jpa:
        show-sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: validate
    #https://www.baeldung.com/spring-boot-customize-jackson-objectmapper
    jackson:
        default-property-inclusion: non-null
        date-format: yyyy-MM-dd HH:mm:ss

# Setup the logging configuration to show sql and prepared statement
# https://www.baeldung.com/sql-logging-spring-boot
logging:
    # config: classpath:/logback-${spring.profiles.active}.xml
    config: classpath:log/logback-dev.xml
    level:
        '[org.hibernate.sql]': debug
        '[org.hibernate.type.descriptor.sql.BasicBinder]': trace
